version: '3.4'

services:
  catalogdb:
    image: postgres:18-alpine

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

volumes:
  postgres_catalog:
  
